### ISSUE TITLE
Pass HTTP Body to Logic Apps workflow

### ISSUE THREAD

**Issue by your-azure-coach** [dapr/workflows#46] opened 2020-06-01 13:51 UTC
Hi!

I have written an HTTP-triggered Logic Apps workflow and it's running successfully in Dapr.  It gets invoked like this:

`POST http://localhost:3500/v1.0/invoke/workflows/method/<workflowname>`

Unfortunately, when I try to access the HTTP request body in the Logic Apps workflow, it seems to be empty.  I use the **@triggerBody()** expression in the response shape to check its value, but it's always empty.  This expression works fine in Azure.

I tried several HTTP variations on the HTTP body, but none of them works...

Any pointers?
Thank you
T.

**Comment by yaron2** [comment] 2020-06-01 13:53
@laveeshb can you assist here?

**Comment by laveeshb** [comment] 2020-06-01 15:58
Sure.
@your-azure-coach can you provide the workflow definition and HTTP request you used? If you had any secrets, please remove those.

**Comment by your-azure-coach** [comment] 2020-06-01 17:08
Thanks for the quick response!  Running on Kubernetes (miniKube).  Attached you can find my repo.
[dapr-logic-apps.zip](https://github.com/dapr/workflows/files/4712464/dapr-logic-apps.zip)

 Assuming you're at its root:

```
kubectl create configmap workflow-order-import-config --from-file ./workflows/order-import.json
kubectl apply -f deploy/deploy.yaml
kubectl port-forward deploy/workflow-order-import-app 3500:3500
```

**Request:**
POST http://localhost:3500/v1.0/invoke/workflows/method/order-import
HTTP BODY = samples/new-orders.json (Content-Type = application/json)

**Response:**
Thanks for submitting your orders!!!  Request: 

**Expected response:**
Thanks for submitting your orders!!!  Request: [insert HTTP request body here]

Because the Logic Apps definition contains: 

`            
"Response": {
                "inputs": {
                    "body": "Thanks for submitting your orders!!!  Request: @{triggerBody()}",
                    "statusCode": 200
                },
                "kind": "Http",
                "runAfter": {},
                "type": "Response"
            }
`
Thanks for looking into it, @laveeshb !

**Comment by laveeshb** [comment] 2020-06-01 17:29
The issue is that the request used to trigger at dapr host is not the same request that gets passed to workflow runtime. 

Here, we create a new request that is passed to the workflow runtime (https://github.com/dapr/workflows/blob/226948e046d538aec03fa63d1521ce39da5fadbb/src/Dapr.Workflows/Workflow/WorkflowRunner.cs#L117).

@yaron2 -- can you make sure the HTTP request from dapr host is passed to workflow runtime for triggering the app?

**Comment by yaron2** [comment] 2020-06-01 17:32
> The issue is that the request used to trigger at dapr host is not the same request that gets passed to workflow runtime.
> 
> Here, we create a new request that is passed to the workflow runtime (
> 
> https://github.com/dapr/workflows/blob/226948e046d538aec03fa63d1521ce39da5fadbb/src/Dapr.Workflows/Workflow/WorkflowRunner.cs#L117
> 
> ).
> @yaron2 -- can you make sure the HTTP request from dapr host is passed to workflow runtime for triggering the app?

Yes, I'll submit a PR soon.

**Comment by your-azure-coach** [comment] 2020-06-08 18:53
Hi @yaron2 , any idea on when we can expect a fix for this?  I am working an a full end-to-end scenario, to share with the community.  Just want to understand if it makes sense to wait for this or to just go ahead an work around it.

Thanks
Toon

**Comment by yaron2** [comment] 2020-06-08 19:03
Will be released this week :)

**Comment by yaron2** [comment] 2020-06-23 04:21
@your-azure-coach this is now fixed on master branch.

**Closed** 2020-06-23 04:20 UTC
Labels: P1

**Comment by yaron2** [comment] 2020-06-23 04:29
@your-azure-coach a new `0.2.1` version for this fix just got released!

To update on Kubernetes, simply re-run:

```
kubectl apply -f https://raw.githubusercontent.com/dapr/workflows/master/deploy/deploy.yaml
```

**Comment by your-azure-coach** [comment] 2020-06-23 14:45
Thanks a lot, @yaron2!  I can confirm hereby that it works as expected!

**Comment by yaron2** [comment] 2020-06-23 14:46
Great :)

/cc @msfussell
